services:

  postgres:
    image: postgres
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "passw0rd!"
    ports:
      - "5432:5432"
    container_name: rent-motorcycle-db

  zookeeper:
      image: confluentinc/cp-zookeeper:latest
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - 2181:2181
  kafka:
      image: confluentinc/cp-kafka:latest
      depends_on:
        - zookeeper
      ports:
        - 9092:9092
        - 29092:29092
      container_name: rent-motorcycle-kafka
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: INSIDE://rent-motorcycle-kafka:9092,OUTSIDE://localhost:29092
        KAFKA_LISTNERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_CREATE_TOPICS: "motorcycle-created:1:1"