###
//API requests using REST Client extension to execute
@api = http://localhost:5115/api

###
# @name getMotorcycles

GET {{api}}/motorcycle  

###
@motoId={{getMotorcycles.response.body.$.result.motorcycles[0].id}}

# @name getMotorcycleById

GET {{api}}/motorcycle/{{motoId}}

###
@plate={{getMotorcycleById.response.body.$.result.motorcycle.plate}}

GET {{api}}/motorcycle
  ?plate={{plate}}

###

POST {{api}}/motorcycle
Content-Type: application/json

{
  "year": 2023,
  "model": "CG",
  "plate": "XXX1234"
}

###

POST {{api}}/motorcycle
Content-Type: application/json

{
  "year": 2024,
  "model": "Titan",
  "plate": "YYY4567"
}

###

PUT {{api}}/motorcycle/{{motoId}}
Content-Type: application/json

{  
  "plate": "YYY0000"
}

###

DELETE {{api}}/motorcycle/{{motoId}}

###
# @name getCustomers

GET {{api}}/customer
  # ?driverLicenseNumber=99999999
  # ?taxId=111111111111

###
# @name getCustomersById
@customId={{getCustomers.response.body.$.result.customers[0].id}}

GET {{api}}/customer/{{customId}}

###

POST {{api}}/customer
Content-Type: application/json

{
  "name" : "Tste",
  "taxId" : "111111111111",
  "bornDate" : "2024-05-30T22:26:09.401Z",
  "driverLicenseNumber" : 888888888,
  "driverLicenseType" : "A"
}

###
@customId={{getCustomersById.response.body.$.result.customer.id}}

PUT {{api}}/customer/{{customId}}
Content-Type: application/json

{      
  "name": "Tste",
  "taxId": "0000000000",
  "bornDate": "2024-05-30T00:00:00",
  "driverLicenseNumber": 99999999,
  "driverLicenseType": "B"
}

###